name: Update badges

on:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 1,15 * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: anisul-kabir
